export const solicitudTypes = {
  SET_SOLICITUD_FORM: 'SET_SOLICITUD_FORM',
  CLEAR_SOLICITUD_FORM: 'CLEAR_SOLICITUD_FORM',
};

export const createSolicitudTypes = {
  REQUEST: 'CREATE_SOLICITUD_REQUEST',
  SUCCESS: 'CREATE_SOLICITUD_SUCCESS',
  FAILURE: 'CREATE_SOLICITUD_FAILURE',
};