export const solicitudTypes = {
  SET_SOLICITUD_FORM: 'SET_SOLICITUD_FORM',
  CLEAR_SOLICITUD_FORM: 'CLEAR_SOLICITUD_FORM',
  CLEAR_WHATSAPP_CODE: 'CLEAR_WHATSAPP_CODE',
  CLEAR_ROSETA_INFO: 'CLEAR_ROSETA_INFO',
};

export const createSolicitudTypes = {
  REQUEST: 'CREATE_SOLICITUD_REQUEST',
  SUCCESS: 'CREATE_SOLICITUD_SUCCESS',
  FAILURE: 'CREATE_SOLICITUD_FAILURE',
};

export const verifySolicitudStateTypes = {
  REQUEST: 'VERIFY_SOLICITUD_STATE_REQUEST',
  SUCCESS: 'VERIFY_SOLICITUD_STATE_SUCCESS',
  FAILURE: 'VERIFY_SOLICITUD_STATE_FAILURE',
};

export const uploadFilesTypes = {
  REQUEST: 'UPLOAD_FILES_REQUEST',
  SUCCESS: 'UPLOAD_FILES_SUCCESS',
  FAILURE: 'UPLOAD_FILES_FAILURE',
};

export const updateSolicitudTypes = {
  REQUEST: 'UPDATE_SOLICITUD_REQUEST',
  SUCCESS: 'UPDATE_SOLICITUD_SUCCESS',
  FAILURE: 'UPDATE_SOLICITUD_FAILURE',
};

export const renewalSolicitudTypes = {
  REQUEST: 'RENEWAL_SOLICITUD_REQUEST',
  SUCCESS: 'RENEWAL_SOLICITUD_SUCCESS',
  FAILURE: 'RENEWAL_SOLICITUD_FAILURE',
};

export const sendWhatsappCodeTypes = {
  REQUEST: 'SEND_WHATSAPP_CODE_REQUEST',
  SUCCESS: 'SEND_WHATSAPP_CODE_SUCCESS',
  FAILURE: 'SEND_WHATSAPP_CODE_FAILURE',
};

export const readRosetaTypes = {
  REQUEST: 'READ_ROSETA_REQUEST',
  SUCCESS: 'READ_ROSETA_SUCCESS',
  FAILURE: 'READ_ROSETA_FAILURE',
};

export const updateRequestType = {
  REQUEST: 'UPDATE_REQUEST_TYPE_REQUEST',
  SUCCESS: 'UPDATE_REQUEST_TYPE_SUCCESS',
  FAILURE: 'UPDATE_REQUEST_TYPE_FAILURE',
};