export const solicitudTypes = {
  SET_SOLICITUD_FORM: 'SET_SOLICITUD_FORM',
  CLEAR_SOLICITUD_FORM: 'CLEAR_SOLICITUD_FORM',
};

export const createSolicitudTypes = {
  REQUEST: 'CREATE_SOLICITUD_REQUEST',
  SUCCESS: 'CREATE_SOLICITUD_SUCCESS',
  FAILURE: 'CREATE_SOLICITUD_FAILURE',
};

export const verifySolicitudStateTypes = {
  REQUEST: 'VERIFY_SOLICITUD_STATE_REQUEST',
  SUCCESS: 'VERIFY_SOLICITUD_STATE_SUCCESS',
  FAILURE: 'VERIFY_SOLICITUD_STATE_FAILURE',
};

export const uploadFilesTypes = {
  REQUEST: 'UPLOAD_FILES_REQUEST',
  SUCCESS: 'UPLOAD_FILES_SUCCESS',
  FAILURE: 'UPLOAD_FILES_FAILURE',
};

export const updateSolicitudTypes = {
  REQUEST: 'UPDATE_SOLICITUD_REQUEST',
  SUCCESS: 'UPDATE_SOLICITUD_SUCCESS',
  FAILURE: 'UPDATE_SOLICITUD_FAILURE',
};